DELETE FROM gift_certificate_price_history;
DELETE FROM order_gift_certificate;
DELETE FROM gift_certificate_tag;
DELETE FROM users_roles;
DELETE FROM roles;
DELETE FROM orders;
DELETE FROM gift_certificate;
DELETE FROM tag;
DELETE FROM users;
